### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by mfherbst** [libAtoms/extxyz#15]
Hi @jameskermode 

We all of a sudden get extxyz-related segfaults in our CI:

https://github.com/JuliaMolSim/DFTK.jl/actions/runs/6275249065/job/17042334245#step:6:4618

Any idea what this could be?

**Comment by mfherbst** [comment]
Just realised you probably can't see the stack trace, here it is:

```
 signal (11): Segmentation fault
in expression starting at /home/runner/work/DFTK.jl/DFTK.jl/examples/atomsbase.jl:37
unknown function (ip: 0x7fe5219b227c)
cleri__kwcache_new at /home/runner/.julia/artifacts/72ff5141af7b192e7773ac6bfbe003b39fb9009c/lib/libcleri.so (unknown line)
cleri_parse2 at /home/runner/.julia/artifacts/72ff5141af7b192e7773ac6bfbe003b39fb9009c/lib/libcleri.so (unknown line)
cleri_parse at /opt/x86_64-linux-gnu/bin/../x86_64-linux-gnu/sys-root/usr/local/include/cleri/parse.h:88
extxyz_read_ll at /workspace/srcdir/extxyz/libextxyz/extxyz.c:609
#read_frame_dicts#7 at /home/runner/.julia/packages/ExtXYZ/a5d5v/src/fileio.jl:208
read_frame_dicts##kw at /home/runner/.julia/packages/ExtXYZ/a5d5v/src/fileio.jl:203 [inlined]
#read_frame#8 at /home/runner/.julia/packages/ExtXYZ/a5d5v/src/fileio.jl:261
read_frame at /home/runner/.julia/packages/ExtXYZ/a5d5v/src/fileio.jl:260 [inlined]
#12 at /home/runner/.julia/packages/ExtXYZ/a5d5v/src/fileio.jl:315
#560 at ./channels.jl:132
unknown function (ip: 0x7fe47450cebf)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:877
Allocations: 3801928836 (Pool: 3794536219; Big: 7392617); GC: 1466
ERROR: LoadError: Package DFTK errored during testing (received signal: 11)
```

**Comment by jameskermode** [comment]
If you dev ExtXYZ this is fixed already. Alternatively you can pin extxyz_jll at v0.1.0.

**Comment by jameskermode** [comment]
I will make a new release of ExtXYZ.jl ASAP to fix this properly, and also add support for reading plain XYZ files.

**Comment by mfherbst** [comment]
Awesome, thanks!

**Comment by mfherbst** [comment]
This is still an issue on our end by the way, causing our documentation build in DFTK to segfault and fail.

**Comment by jameskermode** [comment]
Are you using dev release of ExtXYZ.jl?

**Comment by mfherbst** [comment]
No, but that does not help me because te CI only indirectly installs ExtXYZ from General (as a dependency of other things). As of now the stable release in General is broken, which is why the CI is broken.

**Comment by jameskermode** [comment]
Understood, I'll do a new release. Had been trying to fix something else at the same time but that's taking longer than expected due to difficulties compiling on Windows.

**Comment by mfherbst** [comment]
Thanks, much appreciated @jameskermode :+1:

**Comment by jameskermode** [comment]
ExtXYZ.jl v0.1.14 is tagged and on it's way through the General registry automerge process now
